#ifndef POLYBOARD_LAYOUT_H
#define POLYBOARD_LAYOUT_H

#include "app.h"
#include "app_defs.h"
#include "colors.h"

// Inner pad indexes
static const u8 PAD_INDEXES[PAD_COUNT] = {
    11, 12, 13, 14, 15, 16, 17, 18, 21, 22, 23, 24, 25, 26, 27, 28,
    31, 32, 33, 34, 35, 36, 37, 38, 41, 42, 43, 44, 45, 46, 47, 48,
    51, 52, 53, 54, 55, 56, 57, 58, 61, 62, 63, 64, 65, 66, 67, 68,
    71, 72, 73, 74, 75, 76, 77, 78, 81, 82, 83, 84, 85, 86, 87, 88,
};

static const int LAYOUT_LOGO[PAD_COUNT] = {
    COLOR_WHITE,   COLOR_WHITE,   COLOR_WHITE,   COLOR_WHITE,   COLOR_WHITE,
    COLOR_WHITE,   COLOR_WHITE,   COLOR_WHITE,   COLOR_WHITE,   COLOR_WHITE,
    COLOR_TEAL,    COLOR_TEAL,    COLOR_WHITE,   COLOR_WHITE,   COLOR_WHITE,
    COLOR_WHITE,   COLOR_WHITE,   COLOR_TEAL,    COLOR_WHITE,   COLOR_TEAL,
    COLOR_WHITE,   COLOR_WHITE,   COLOR_WHITE,   COLOR_WHITE,   COLOR_WHITE,
    COLOR_TEAL,    COLOR_TEAL,    COLOR_WHITE,   COLOR_WHITE,   COLOR_WHITE,
    COLOR_MAGENTA, COLOR_WHITE,   COLOR_WHITE,   COLOR_TEAL,    COLOR_WHITE,
    COLOR_WHITE,   COLOR_WHITE,   COLOR_MAGENTA, COLOR_MAGENTA, COLOR_WHITE,
    COLOR_WHITE,   COLOR_WHITE,   COLOR_WHITE,   COLOR_WHITE,   COLOR_MAGENTA,
    COLOR_WHITE,   COLOR_MAGENTA, COLOR_WHITE,   COLOR_WHITE,   COLOR_WHITE,
    COLOR_WHITE,   COLOR_WHITE,   COLOR_MAGENTA, COLOR_MAGENTA, COLOR_WHITE,
    COLOR_WHITE,   COLOR_WHITE,   COLOR_WHITE,   COLOR_WHITE,   COLOR_WHITE,
    COLOR_WHITE,   COLOR_WHITE,   COLOR_WHITE,   COLOR_WHITE,
};

/**
 * Renders the layout on the pads.
 *
 * @param layout The layout to render.
 */
void render_layout(const int layout[PAD_COUNT]);

#endif // POLYBOARD_LAYOUT_H
