name: Release

on:
  push:
    tags:
      - v**

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: carlosperate/arm-none-eabi-gcc-action@v1
      - name: build
        run: make
      - name: test
        run: test -f build/launchpad_pro.syx
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/launchpad_pro.syx
          generate_release_notes: true
